const seedData = [
  {
    name: 'Chicken Alfredo Fettuccine',
    description:
      'A creamy and indulgent pasta dish featuring tender chicken and rich Alfredo sauce.',
    author: 'justin',
    cookTime: '30 minutes',
    image: 'https://live.staticflickr.com/65535/51950457225_be17bde5f9_b.jpg',
    ingredients: [
      '8 oz fettuccine pasta',
      '2 boneless, skinless chicken breasts',
      '2 tablespoons butter',
      '2 cloves garlic, minced',
      '1 cup heavy cream',
      '1 cup grated Parmesan cheese',
      'Salt and pepper to taste',
      'Fresh parsley for garnish',
    ],
    instruction: [
      '1. Cook the fettuccine pasta according to package instructions. Drain and set aside.',
      '2. Season the chicken breasts with salt and pepper. In a large skillet, melt the butter over medium-high heat. Add the chicken and cook until no longer pink inside. Remove the chicken and set aside.',
      '3. In the same skillet, add minced garlic and sauté until fragrant.',
      '4. Pour in the heavy cream and bring it to a simmer. Stir in the grated Parmesan cheese and continue to cook until the sauce thickens.',
      '5. Slice the cooked chicken and add it to the sauce.',
      '6. Serve the Alfredo sauce over cooked fettuccine, garnished with fresh parsley.',
    ],
    curatorFavorited: true,
    cheerCount: 0,
    categoryId: '65296816d8eac7c4032399df',
  },
  {
    name: 'Homestyle Chili',
    description: 'A hearty and delicious homemade chili recipe',
    author: 'justin',
    cookTime: '4 hours',
    image: 'https://live.staticflickr.com/8298/7818571354_8e0c5ee56e_b.jpg',
    ingredients: [
      '1 lb ground beef',
      '1 onion, chopped',
      '1 red bell pepper, diced',
      '2 cans (15 oz each) of kidney beans, drained and rinsed',
      '1 can (28 oz) crushed tomatoes',
      '1 can (8 oz) tomato sauce',
      '2 cloves of garlic, minced',
      '2 tablespoons chili powder',
      '1 teaspoon cumin',
      '1/2 teaspoon paprika',
      'Salt and pepper to taste',
      'Shredded cheddar cheese (for topping)',
      'Sour cream (for topping)',
      'Chopped green onions (for topping)',
      'Sliced jalapeños (for topping)',
    ],
    instruction: [
      '1. In a large skillet, cook the ground beef over medium heat until browned. Drain excess fat.',
      '2. Add chopped onions and red bell pepper to the skillet. Sauté until the vegetables are tender.',
      '3. Transfer the beef and vegetable mixture to a slow cooker.',
      '4. Add kidney beans, crushed tomatoes, tomato sauce, minced garlic, chili powder, cumin, paprika, salt, and pepper to the slow cooker. Stir to combine.',
      '5. Cover and cook on low for 4 hours, or until the chili is heated through and flavors meld.',
      '6. Serve hot, garnished with shredded cheddar cheese, a dollop of sour cream, chopped green onions, and sliced jalapeños.',
    ],
    curatorFavorited: true,
    cheerCount: 0,
    categoryId: '652959a34a399aba12878201',
  },
  {
    name: 'Chicken Tandoori Skewers',
    description: 'Tender and flavorful Indian-style chicken skewers with tandoori spices.',
    author: 'justin',
    cookTime: '40 minutes',
    image: 'https://live.staticflickr.com/3009/2868394097_793704cd7e_b.jpg',
    ingredients: [
      '1 lb chicken breast, cut into cubes',
      '1/2 cup plain yogurt',
      '2 tablespoons tandoori spice mix',
      '1 lemon, juiced',
      '2 cloves garlic, minced',
      '1-inch piece of ginger, grated',
      '1 red onion, cut into chunks',
      'Bell peppers, assorted colors, cut into chunks',
      'Wooden skewers, soaked in water',
      'Salt and pepper to taste',
      'Fresh cilantro (for garnish)',
    ],
    instruction: [
      '1. In a bowl, combine plain yogurt, tandoori spice mix, lemon juice, minced garlic, and grated ginger to make the marinade.',
      '2. Add the chicken cubes to the marinade, ensuring they are well coated. Cover and refrigerate for at least 30 minutes, or longer for better flavor.',
      '3. Preheat your grill or oven to medium-high heat.',
      '4. Thread marinated chicken, red onion, and bell peppers onto the soaked skewers, alternating between them.',
      '5. Season the skewers with salt and pepper.',
      '6. Grill or bake the skewers for about 15-20 minutes, turning occasionally, until the chicken is fully cooked and has a nice char.',
      '7. Garnish with fresh cilantro and serve hot.',
    ],
    curatorFavorited: true,
    cheerCount: 0,
    categoryId: '65295d044a399aba12878206',
  },
  {
    name: 'Creamy Tomato Basil Pasta',
    description: 'A simple and comforting pasta dish with a creamy tomato and basil sauce.',
    author: 'justin',
    cookTime: '25 minutes',
    image: 'https://live.staticflickr.com/1855/43911601344_f75d760928_b.jpg',
    ingredients: [
      '8 oz penne pasta',
      '1 can (14 oz) diced tomatoes',
      '1/2 cup heavy cream',
      '2 cloves garlic, minced',
      '1/4 cup fresh basil leaves, chopped',
      '2 tablespoons olive oil',
      '1/2 teaspoon red pepper flakes',
      'Salt and pepper to taste',
      'Grated Parmesan cheese (for topping)',
      'Fresh basil leaves (for garnish)',
    ],
    instruction: [
      '1. Cook the penne pasta according to package instructions. Drain and set aside.',
      '2. In a large skillet, heat the olive oil over medium heat. Add minced garlic and red pepper flakes, and sauté until fragrant.',
      '3. Pour in the diced tomatoes and heavy cream. Stir and let it simmer for a few minutes.',
      '4. Add the chopped basil leaves and season with salt and pepper.',
      '5. Toss the cooked penne pasta in the creamy tomato basil sauce until well coated.',
      '6. Serve hot, garnished with grated Parmesan cheese and fresh basil leaves.',
    ],
    curatorFavorited: false,
    cheerCount: 0,
    categoryId: '65296816d8eac7c4032399df',
  },
  {
    name: 'Beef and Broccoli Stir-Fry',
    description: 'A quick and flavorful Chinese-inspired stir-fry with tender beef and broccoli.',
    author: 'justin',
    cookTime: '20 minutes',
    image: 'https://live.staticflickr.com/8660/28265304420_151ff85449_b.jpg',
    ingredients: [
      '1 lb flank steak, thinly sliced',
      '3 cups broccoli florets',
      '1/4 cup soy sauce',
      '2 tablespoons oyster sauce',
      '2 cloves garlic, minced',
      '1-inch piece of ginger, grated',
      '2 tablespoons vegetable oil',
      '1 teaspoon cornstarch',
      'Sesame seeds (for garnish)',
      'Cooked rice (for serving)',
      'Salt and pepper to taste',
    ],
    instruction: [
      '1. In a small bowl, whisk together soy sauce, oyster sauce, minced garlic, and grated ginger to make the sauce. Set aside.',
      "2. In a separate bowl, combine the sliced beef with cornstarch, salt, and pepper, ensuring it's well coated.",
      "3. Heat vegetable oil in a wok or large skillet over high heat. Add the beef and stir-fry for 2-3 minutes or until it's no longer pink. Remove the beef from the wok and set aside.",
      '4. In the same wok, add the broccoli florets and stir-fry for 2-3 minutes until they turn bright green and tender.',
      '5. Return the cooked beef to the wok and pour the sauce over the beef and broccoli. Stir-fry for another 2 minutes or until the sauce thickens and coats the ingredients.',
      '6. Serve hot over cooked rice, garnished with sesame seeds.',
    ],
    curatorFavorited: false,
    cheerCount: 0,
    categoryId: '65299b36f9a581c0f5470aa4',
  },
  {
    name: 'Spicy Black Bean Enchiladas',
    description: 'A zesty and satisfying Mexican dish filled with spicy black beans and cheese.',
    author: 'justin',
    cookTime: '35 minutes',
    image: 'https://live.staticflickr.com/5262/5606538276_aae7750db6_b.jpg',
    ingredients: [
      '1 can (15 oz) black beans, drained and rinsed',
      '1 cup cooked rice',
      '1 cup shredded cheddar cheese',
      '1 cup salsa',
      '2 teaspoons chili powder',
      '1/2 teaspoon cumin',
      '1/2 teaspoon paprika',
      '8 small flour tortillas',
      'Sour cream (for topping)',
      'Sliced green onions (for topping)',
      'Sliced olives (for topping)',
      'Cilantro leaves (for garnish)',
    ],
    instruction: [
      '1. Preheat your oven to 350°F (175°C).',
      '2. In a bowl, mix the black beans, cooked rice, half of the shredded cheddar cheese, salsa, chili powder, cumin, and paprika to create the filling.',
      '3. Spoon the filling into the flour tortillas and roll them up tightly. Place the filled tortillas seam-side down in a baking dish.',
      '4. Sprinkle the remaining cheddar cheese on top of the rolled tortillas.',
      '5. Bake in the preheated oven for 20-25 minutes, or until the enchiladas are heated through and the cheese is bubbly and golden.',
      '6. Serve hot, topped with a dollop of sour cream, sliced green onions, sliced olives, and garnished with fresh cilantro leaves.',
    ],
    curatorFavorited: true,
    cheerCount: 0,
    categoryId: '652965646691718274490be6',
  },
  {
    name: 'Grilled Teriyaki Salmon',
    description: 'Delicious teriyaki-glazed salmon fillets, grilled to perfection.',
    author: 'justin',
    cookTime: '20 minutes',
    image: 'https://live.staticflickr.com/8069/8190675474_6cd013a903_b.jpg',
    ingredients: [
      '4 salmon fillets',
      '1/2 cup teriyaki sauce',
      '2 tablespoons brown sugar',
      '1 teaspoon ginger, minced',
      '1 teaspoon garlic, minced',
      'Sesame seeds (for garnish)',
      'Green onions (for garnish)',
    ],
    instruction: [
      '1. In a bowl, mix teriyaki sauce, brown sugar, minced ginger, and minced garlic to make the marinade.',
      '2. Marinate salmon fillets in the mixture for 15 minutes.',
      '3. Preheat the grill to medium-high heat and oil the grates.',
      '4. Grill salmon for 4-5 minutes on each side, basting with the marinade.',
      '5. Serve hot, garnished with sesame seeds and green onions.',
    ],
    curatorFavorited: false,
    cheerCount: 0,
    categoryId: '652966106691718274490be9',
  },
  {
    name: 'Thai Green Curry Chicken',
    description: 'A fragrant and spicy Thai green curry with tender chicken and vegetables.',
    author: 'justin',
    cookTime: '30 minutes',
    image: 'https://live.staticflickr.com/4039/4525779184_64b6875db7_b.jpg',
    ingredients: [
      '2 chicken breasts, sliced',
      '1 can (14 oz) coconut milk',
      '2 tablespoons green curry paste',
      '1 cup bell peppers, sliced',
      '1 cup zucchini, sliced',
      'Basil leaves (for garnish)',
      'Jasmine rice (for serving)',
    ],
    instruction: [
      '1. In a large skillet, heat the coconut milk and green curry paste over medium heat.',
      '2. Add sliced chicken and simmer until cooked through.',
      '3. Stir in bell peppers and zucchini and cook until tender.',
      '4. Serve hot over jasmine rice, garnished with fresh basil leaves.',
    ],
    curatorFavorited: false,
    cheerCount: 0,
    categoryId: '65299b36f9a581c0f5470aa4',
  },
  {
    name: 'Vegetarian Tofu Stir-Fry',
    description: 'A colorful and healthy stir-fry with tofu and an array of crisp vegetables.',
    author: 'justin',
    cookTime: '25 minutes',
    image: 'https://live.staticflickr.com/3132/5860966787_97a0214640_b.jpg',
    ingredients: [
      '1 block of firm tofu, cubed',
      '2 cups broccoli florets',
      '1 cup bell peppers, sliced',
      '1 cup snap peas',
      '1/4 cup soy sauce',
      '2 tablespoons hoisin sauce',
      '1 tablespoon sesame oil',
      'Rice or noodles (for serving)',
    ],
    instruction: [
      '1. In a large wok or skillet, heat sesame oil over high heat.',
      '2. Add cubed tofu and stir-fry until lightly browned on all sides. Remove from the pan and set aside.',
      '3. In the same pan, stir-fry broccoli, bell peppers, and snap peas until tender-crisp.',
      '4. Add tofu back to the pan, and pour in soy sauce and hoisin sauce. Stir to combine and heat through.',
      '5. Serve hot over rice or noodles.',
    ],
    curatorFavorited: false,
    cheerCount: 0,
    categoryId: '65299b36f9a581c0f5470aa4',
  },
  {
    name: 'Greek Salad',
    description:
      'A refreshing and colorful Greek salad with crisp veggies, olives, and feta cheese.',
    author: 'justin',
    cookTime: '15 minutes',
    image: 'https://live.staticflickr.com/2420/3821728990_2eaf7088af_b.jpg',
    ingredients: [
      '2 cucumbers, diced',
      '2 tomatoes, diced',
      '1 red onion, thinly sliced',
      '1 cup Kalamata olives',
      '1 cup feta cheese, crumbled',
      '1/4 cup extra-virgin olive oil',
      '2 tablespoons red wine vinegar',
      'Fresh oregano leaves (for garnish)',
    ],
    instruction: [
      '1. In a large bowl, combine diced cucumbers, tomatoes, sliced red onion, Kalamata olives, and crumbled feta cheese.',
      '2. In a small bowl, whisk together extra-virgin olive oil and red wine vinegar to make the dressing.',
      '3. Pour the dressing over the salad and toss to combine.',
      '4. Garnish with fresh oregano leaves and serve immediately.',
    ],
    curatorFavorited: false,
    cheerCount: 0,
    categoryId: '65296816d8eac7c4032399df',
  },
  {
    name: 'Southern Fried Chicken',
    description: 'Crispy and succulent fried chicken with a touch of Southern flavor.',
    author: 'justin',
    cookTime: '40 minutes',
    image: 'https://live.staticflickr.com/4030/5156579608_fb21360a6f_b.jpg',
    ingredients: [
      '4 chicken drumsticks',
      '4 chicken thighs',
      '1 cup buttermilk',
      '2 cups all-purpose flour',
      '2 tablespoons paprika',
      '1 tablespoon garlic powder',
      '1 tablespoon onion powder',
      'Salt and pepper to taste',
      'Vegetable oil (for frying)',
    ],
    instruction: [
      '1. In a bowl, soak chicken pieces in buttermilk for 20 minutes.',
      '2. In a separate bowl, combine flour, paprika, garlic powder, onion powder, salt, and pepper.',
      '3. Heat vegetable oil in a deep skillet or cast-iron pan over medium-high heat.',
      '4. Dredge buttermilk-soaked chicken pieces in the flour mixture, ensuring they are well coated.',
      '5. Fry chicken in hot oil until golden brown and cooked through, about 15-20 minutes.',
      '6. Drain on paper towels and serve hot.',
    ],
    curatorFavorited: true,
    cheerCount: 0,
    categoryId: '652959a34a399aba12878201',
  },
  {
    name: 'Classic American Cheeseburger',
    description: 'A timeless and delicious cheeseburger, perfect for a taste of America.',
    author: 'justin',
    cookTime: '20 minutes',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/5/58/190524-classic-american-cheeseburger-ew-207p.jpg',
    ingredients: [
      '1/2 lb ground beef',
      'Hamburger bun',
      'American cheese slice',
      'Lettuce, tomato, and onion slices',
      'Ketchup and mustard',
      'Salt and pepper to taste',
    ],
    instruction: [
      '1. Preheat a grill or stovetop pan over medium-high heat.',
      '2. Season the ground beef with salt and pepper and shape it into a patty.',
      '3. Grill the patty for 3-4 minutes per side until it reaches your desired doneness.',
      '4. Toast the hamburger bun on the grill for a minute or so.',
      '5. Assemble the burger: place the patty on the bun, add cheese, lettuce, tomato, onion, ketchup, and mustard.',
      '6. Serve hot.',
    ],
    curatorFavorited: true,
    cheerCount: 0,
    categoryId: '652d970085e040cf3e77cef0',
  },
  {
    name: 'Cajun Shrimp and Grits',
    description:
      'A spicy and comforting Southern dish featuring Cajun-seasoned shrimp and creamy grits.',
    author: 'justin',
    cookTime: '30 minutes',
    image: 'https://live.staticflickr.com/4144/5097297999_6cd2b94aed_b.jpg',
    ingredients: [
      '1 lb large shrimp, peeled and deveined',
      '1 cup stone-ground grits',
      '2 cups chicken broth',
      '2 cups water',
      '1/2 cup heavy cream',
      '2 tablespoons butter',
      'Cajun seasoning',
      'Green onions (for garnish)',
      'Lemon wedges (for serving)',
    ],
    instruction: [
      '1. Prepare the grits: In a saucepan, bring chicken broth and water to a boil. Stir in the grits and cook according to package instructions. Stir in heavy cream and butter.',
      '2. Season the shrimp generously with Cajun seasoning.',
      '3. In a large skillet, cook the seasoned shrimp for 2-3 minutes per side until they turn pink and slightly charred.',
      '4. Serve the shrimp over a bed of creamy grits, garnished with green onions and lemon wedges.',
    ],
    curatorFavorited: true,
    cheerCount: 0,
    categoryId: '652959a34a399aba12878201',
  },
  {
    name: 'American Apple Pie',
    description: 'A classic American dessert with a flaky crust and sweet apple filling.',
    author: 'justin',
    cookTime: '60 minutes',
    image: 'https://live.staticflickr.com/6184/6076181270_90d8fc4fff_b.jpg',
    ingredients: [
      '2 prepared pie crusts (bottom and top)',
      '6 cups sliced apples (e.g., Granny Smith)',
      '3/4 cup granulated sugar',
      '1 tablespoon lemon juice',
      '1/2 teaspoon cinnamon',
      '1/4 teaspoon nutmeg',
      '2 tablespoons butter',
      '1 egg (for egg wash)',
      'Sugar (for sprinkling)',
    ],
    instruction: [
      '1. Preheat your oven to 425°F (220°C).',
      '2. In a large bowl, combine sliced apples, granulated sugar, lemon juice, cinnamon, and nutmeg.',
      '3. Line a pie dish with the bottom pie crust. Fill with the apple mixture and dot with butter.',
      '4. Place the top crust over the filling, seal the edges, and cut slits in the top for venting.',
      '5. Brush the top crust with beaten egg and sprinkle with sugar.',
      '6. Bake for 45-50 minutes or until the pie is golden brown and the filling is bubbling.',
      '7. Let cool before serving.',
    ],
    curatorFavorited: true,
    cheerCount: 0,
    categoryId: '652d970085e040cf3e77cef0',
  },
  {
    name: 'BBQ Pulled Pork Sandwiches',
    description: 'Tender pulled pork with smoky barbecue sauce, piled high on soft buns.',
    author: 'justin',
    cookTime: '8 hours',
    image: 'https://live.staticflickr.com/6197/6059258356_20f216210b_b.jpg',
    ingredients: [
      '3 lbs pork shoulder',
      '1 cup barbecue sauce',
      '1/4 cup apple cider vinegar',
      '1 onion, sliced',
      '4 hamburger buns',
      'Coleslaw (for topping)',
      'Pickles (for garnish)',
      'Salt and pepper to taste',
    ],
    instruction: [
      '1. Season the pork shoulder with salt and pepper. Place it in a slow cooker.',
      '2. In a bowl, mix barbecue sauce and apple cider vinegar. Pour the mixture over the pork shoulder.',
      '3. Add sliced onions to the slow cooker.',
      '4. Cook on low for 8 hours or until the pork is tender and can be easily shredded.',
      '5. Shred the pork and serve on hamburger buns with coleslaw and pickles.',
    ],
    curatorFavorited: true,
    cheerCount: 0,
    categoryId: '65295d044a399aba12878206',
  },
  {
    name: 'Grilled BBQ Chicken',
    description: 'Juicy chicken pieces marinated in barbecue sauce and grilled to perfection.',
    author: 'justin',
    cookTime: '25 minutes',
    image: 'https://live.staticflickr.com/4075/4753260669_d8bf710313_b.jpg',
    ingredients: [
      '4 bone-in, skin-on chicken thighs',
      '1 cup barbecue sauce',
      '2 tablespoons olive oil',
      '1 teaspoon paprika',
      '1 teaspoon garlic powder',
      'Salt and pepper to taste',
    ],
    instruction: [
      '1. In a bowl, combine barbecue sauce, olive oil, paprika, garlic powder, salt, and pepper.',
      '2. Coat chicken thighs with the marinade and let them sit for 10-15 minutes.',
      '3. Preheat the grill to medium-high heat.',
      "4. Grill chicken for 6-8 minutes per side until it's fully cooked and has grill marks.",
      '5. Serve hot, basting with additional barbecue sauce if desired.',
    ],
    curatorFavorited: true,
    cheerCount: 0,
    categoryId: '65295d044a399aba12878206',
  },
  {
    name: 'BBQ Ribs',
    description: 'Fall-off-the-bone tender ribs with a smoky barbecue glaze.',
    author: 'justin',
    cookTime: '4 hours',
    image: 'https://live.staticflickr.com/4082/4897726842_5a050dd4a3_b.jpg',
    ingredients: [
      '2 racks of baby back ribs',
      '1 cup barbecue sauce',
      '1/4 cup apple cider vinegar',
      '2 tablespoons brown sugar',
      '1 tablespoon paprika',
      '1 teaspoon garlic powder',
      'Salt and pepper to taste',
    ],
    instruction: [
      '1. Remove the membrane from the back of the ribs. Season with salt, pepper, paprika, and garlic powder.',
      '2. Wrap the ribs in aluminum foil and bake at 275°F (135°C) for 2.5 hours.',
      '3. In a bowl, mix barbecue sauce, apple cider vinegar, and brown sugar.',
      '4. Unwrap the ribs, brush with the barbecue sauce mixture, and grill for an additional 30 minutes, basting with sauce.',
      '5. Serve the ribs hot, with extra barbecue sauce on the side.',
    ],
    curatorFavorited: true,
    cheerCount: 0,
    categoryId: '65295d044a399aba12878206',
  },
  {
    name: 'BBQ Tofu Skewers',
    description:
      'Vegetarian skewers with tofu and assorted vegetables, glazed with barbecue sauce.',
    author: 'justin',
    cookTime: '30 minutes',
    image:
      'https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/px610407-image-kwvxjyrj.jpg?w=1200&h=1200&dpr=1&fit=clip&crop=default&fm=jpg&q=75&vib=3&con=3&usm=15&cs=srgb&bg=F4F4F3&ixlib=js-2.2.1&s=33e09492d6f53adccfa21ee1f6abb430',
    ingredients: [
      '1 block of firm tofu, cubed',
      'Assorted vegetables (bell peppers, zucchini, onions, etc.), cut into chunks',
      '1 cup barbecue sauce',
      '2 tablespoons olive oil',
      'Salt and pepper to taste',
      'Wooden skewers, soaked in water',
    ],
    instruction: [
      '1. In a bowl, mix barbecue sauce, olive oil, salt, and pepper.',
      '2. Thread tofu and assorted vegetables onto the soaked skewers, alternating between them.',
      '3. Preheat your grill to medium-high heat.',
      '4. Grill skewers for 4-5 minutes per side, basting with barbecue sauce until caramelized.',
      '5. Serve hot, with extra barbecue sauce for dipping.',
    ],
    curatorFavorited: false,
    cheerCount: 0,
    categoryId: '65295d044a399aba12878206',
  },
];

module.exports = seedData;
